app = "eternal-garden-52091a5b-f518-4d3b-824e-97fc11ab31e0"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'
DEPLOY_ID = '8604af98-80fa-422f-badb-2d2a8f9cccb3'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
